version: '3.8'

services:
  trackd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asc-track-designer
    ports:
      - "8080:8080"
    volumes:
      - ./data:/root/data
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - trackd-network

networks:
  trackd-network:
    driver: bridge
